### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by maeda88** [maeda88/furima-39973#24]
# URL
https://furima-39973.onrender.com

# Basic認証
ID:  admin  パスワード: 2222

# 出品者用
メールアドレス: aaa@aaa   パスワード: 111111a

# 購入者用
メールアドレス: bbb@bbb  パスワード: 111111a

**Comment by mo1015** [comment]
@maeda88 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
12項目表示されています。「ベビー・キッズ」で1項目としましょう。
<img width="376" alt="スクリーンショット 2024-03-04 11 26 06" src="https://github.com/maeda88/furima-39973/assets/62644781/14f7d6b0-a99c-470d-88d4-b06db5845645">

- [x] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
計算が合わず、販売利益が正しく表示されていません。
<img width="594" alt="スクリーンショット 2024-03-04 11 27 02" src="https://github.com/maeda88/furima-39973/assets/62644781/758711c1-b698-4126-b5ff-b685e6d7e1f4">


- [x] **配送先の情報として、郵便番号・都道府県・市区町村・番地・電話番号が必須であること**
都道府県を入力しなくても購入ができてしまいます。都道府県の情報を必須としましょう。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by maeda88** [comment]
ご指摘ありがとうございます。
修正しましたので、ご確認お願いします。

**Comment by mo1015** [comment]
@maeda88 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
